PAYLAPMEXT-123 + Sonar
PaylinePaymentMethod/payment-method-docapost pull request #15
Opened 2019-03-25 09:46 UTC by splanard-thales

* PAYLAPMEXT-123 : renvoi des données de paiement dans la `PaymentResponseSuccess` (fin du step 3)
* Correction de plusieurs problèmes graves remontés par Sonar

2019-03-27 15:01 UTC, splanard-thales commented
Ajout du repo maven-mixed pour pouvoir utiliser les versions SNAPSHOT de la PM-API sur Jenkins
Puis 'squash'

2019-06-27 13:08 UTC, splanard-thales commented
Rebase suite à la création de la v1.1

2019-10-18 09:08 UTC, CharlelieBouvier requested changes

2019-10-18 09:08 UTC, CharlelieBouvier commented on src/main/java/com/payline/payment/docapost/service/impl/PaymentServiceStep02.java
> +                    LOGGER.debug("MandateCreateXmlResponse error : {}", xmlErrorResponse.toString());
Utiliser une lambda pour le paramètre, le toString va être executé alors qu'on est jamais en level debug

LOGGER.debug("MandateCreateXmlResponse error : {}", xmlErrorResponse::toString);

2019-10-18 09:08 UTC, CharlelieBouvier commented on src/main/java/com/payline/payment/docapost/service/impl/PaymentServiceStep03.java
> +                    LOGGER.debug("SddOrderCreateCreateXmlResponse error : {}", xmlErrorResponse.toString());
même chose ici, lambda svp

2019-10-18 09:08 UTC, CharlelieBouvier commented on src/main/java/com/payline/payment/docapost/service/impl/RefundServiceImpl.java
> +            LOGGER.debug("SddOrderCreateResponse : {}", xmlErrorResponse.toString());
même chose ici, lambda svp

2019-10-18 09:08 UTC, CharlelieBouvier commented on src/main/java/com/payline/payment/docapost/service/impl/ResetServiceImpl.java
> +            LOGGER.debug("OrderCancelResponse : {}", orderCancelResponse.toString());
même chose ici, lambda svp

2019-10-18 09:08 UTC, CharlelieBouvier commented on src/main/java/com/payline/payment/docapost/service/impl/ResetServiceImpl.java
> +            LOGGER.debug("OrderCancelResponse : {}", xmlErrorResponse.toString());
même chose ici, lambda svp

2019-10-18 09:08 UTC, CharlelieBouvier commented on src/main/java/com/payline/payment/docapost/utils/DocapostFormUtils.java
> +        //ConfigEnvironment env = PluginUtils.getEnvironnement(request);
supprimer le code commenter s'il n'a pas sa place

2019-10-23 07:46 UTC, CharlelieBouvier commented
Bonjour, serait-il possible de squasher la branche svp?

2019-10-23 15:48 UTC, CharlelieBouvier approved these changes

2019-10-23 15:48 UTC, merged